name: the_guide
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  commander_ui: ^2.4.0
  dotenv: ^4.2.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0


dev_dependencies:
  build_runner: ^2.8.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  lints: ^5.0.0
  test: ^1.24.0
