name: the_guide
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ^3.32.0

# Add regular dependencies here.
dependencies:
  flutter: 
    sdk: flutter

  collection: ^1.18.0

  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  equatable: ^2.0.7  

  path_provider: ^2.1.5

  flutter_dotenv: ^5.1.0
  http: ^1.5.0

  provider: ^6.1.5+1

  file_saver: ^0.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.8.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
  generate: true
  assets: 
    - .env
  #   - path/to/asset

